language: java
jdk:
  - oraclejdk9
sudo: required
branches:
  - develop
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
addons:
  postgresql: "9.6"
  services:
    - postgresql
  before_script:
    - psql -c "create user docker with password 'docker';" -U postgres
    - psql -c "create database drive_db;" -U postgres
    - psql -c "grant all on database drive_db to docker;" -U postgres